image: node:alpine

stages:
  - setup
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}${CI_JOB_ID}

variables:
  GIT_SUBMODULE_STRATEGY: recursive

install_node_modules:
  stage: setup
  script:
    - npm install
  cache:
    paths:
    - node_modules/

build_next:
  stage: build
  script:
    - cp .env.example .env
    - npm run build
  cache:
    paths:
    - node_modules/
    - src/.next/
    - .env

lint:
  stage: test
  script: npm run lint
  cache:
    paths:
    - node_modules/

jest:
  stage: test
  script: npm run test:unit:coverage
  coverage: '/^Statements\s*:\s*([^%]+)/'
  cache:
    paths:
    - node_modules/

e2e:
  stage: test
  script:
    - apk add --no-cache netcat-openbsd bash
    - npm run test:e2e:ci
  cache:
    paths:
    - node_modules/
    - src/.next/
    - .env

deploy_staging:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$STAGING_PRIVKEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$STAGING_SERVER_PUBKEY" > ~/.ssh/known_hosts
  script:
    - ssh -o PasswordAuthentication=no -o PreferredAuthentications=publickey -i ~/.ssh/id_rsa $STAGING_SERVER_USER@$STAGING_SERVER "$STAGING_DEPLOY_CMD"
  environment: staging
  only:
    - master
  cache: {}
