image: node:latest

stages:
  - deploy
  - setup
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - src/.next/
  - .env

variables:
  GIT_SUBMODULE_STRATEGY: recursive

install_node_modules:
  stage: setup
  script:
    - npm install

build_next:
  stage: build
  script:
    - cp .env.example .env
    - npm run build

lint:
  stage: test
  script: npm run lint

jest:
  stage: test
  script: npm run test:coverage
  coverage: '/^Statements\s*:\s*([^%]+)/'

deploy_staging:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$STAGING_PRIVKEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    script:
    - ssh -o PasswordAuthentication=no -o PreferredAuthentications=publickey -i ~/.ssh/id_rsa $STAGING_SERVER_USER@$STAGING_SERVER "$STAGING_DEPLOY_CMD"
  environment: staging
  only:
    - gitlab-cd-deploy
