image: docker:latest

stages:
  - build
  - test
  - release
  - deploy

variables:
  IMAGE_STAGING_TAG: $CI_REGISTRY_IMAGE/staging:latest
  IMAGE_RELEASE_TAG: $CI_REGISTRY_IMAGE:latest

.docker-default-vars: &docker-default-vars
  GIT_STRATEGY: none
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE/staging:$CI_COMMIT_REF_SLUG
  IMAGE_E2E_CACHE_TAG: $CI_REGISTRY_IMAGE/e2e:cache
  IMAGE_E2E_TAG: $CI_REGISTRY_IMAGE/e2e:$CI_COMMIT_REF_SLUG
  # taken from https://github.com/semver/semver/issues/232#issue-48635632
  SEMVER_REGEXP: '^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$'

.docker-base: &docker-base
  services:
    - docker:dind
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin "$CI_REGISTRY"
  after_script:
    - docker logout "$CI_REGISTRY"
  variables:
    <<: *docker-default-vars

Build image:
  <<: *docker-base
  stage: build
  script:
    - docker pull "$IMAGE_TAG" || true
    - docker pull "$IMAGE_STAGING_TAG" || true
    - docker pull "$IMAGE_RELEASE_TAG" || true
    - docker build --pull --cache-from "$IMAGE_TAG" --cache-from "$IMAGE_STAGING_TAG" --cache-from "$IMAGE_RELEASE_TAG" --tag "$IMAGE_TAG" .
    - docker push "$IMAGE_TAG"
  variables:
    <<: *docker-default-vars
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: recursive

Linting:
  <<: *docker-base
  stage: test
  script:
    - docker pull "$IMAGE_TAG"
    - docker run "$IMAGE_TAG" yarn lint

Unit tests:
  <<: *docker-base
  stage: test
  script:
    - docker pull "$IMAGE_TAG"
    - docker run "$IMAGE_TAG" yarn test:unit:coverage
  coverage: '/^All files\s+\|\s+([0-9.]+)\s+\|\s+/'

E2E tests:
  <<: *docker-base
  stage: test
  script:
    - docker pull "$IMAGE_TAG"
    - docker pull "$IMAGE_E2E_CACHE_TAG" || true
    - docker build --pull --cache-from "$IMAGE_TAG" --cache-from "$IMAGE_E2E_CACHE_TAG" --tag "$IMAGE_E2E_TAG" --build-arg BUILD_IMAGE="$IMAGE_TAG" -f Dockerfile.e2e .
    - docker tag "$IMAGE_E2E_TAG" "$IMAGE_E2E_CACHE_TAG"
    - docker push "$IMAGE_E2E_CACHE_TAG"
    - docker run "$IMAGE_E2E_TAG"
  variables:
    <<: *docker-default-vars
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: none

Push to GitLab registry (staging):
  <<: *docker-base
  stage: release
  script:
    - docker pull "$IMAGE_TAG"
    - docker tag "$IMAGE_TAG" "$IMAGE_STAGING_TAG"
    - docker push "$IMAGE_STAGING_TAG"
  only:
    - dev

Push to GitLab registry (production):
  <<: *docker-base
  stage: release
  script:
    - docker pull "$IMAGE_TAG"
    - docker tag "$IMAGE_TAG" "$IMAGE_RELEASE_TAG"
    - docker push "$IMAGE_RELEASE_TAG"
  only:
    - master

Push to Docker Hub:
  <<: *docker-base
  stage: release
  script:
    - if echo "$CI_COMMIT_TAG" | grep -qvE "$SEMVER_REGEXP"; then echo "Not a semver tag. Happily skipping..."; exit 0; fi
    - docker pull "$IMAGE_TAG"
    - docker tag "$IMAGE_TAG" "$CI_REGISTRY_IMAGE":"${CI_COMMIT_TAG#v}"
    - docker push "$CI_REGISTRY_IMAGE":"${CI_COMMIT_TAG#v}"
    - echo "$DOCKER_HUB_PWD" | docker login --username "$DOCKER_HUB_USER" --password-stdin "$DOCKER_HUB_REGISTRY"
    - docker tag "$IMAGE_TAG" "$DOCKER_HUB_REGISTRY_IMAGE":"${CI_COMMIT_TAG#v}"
    - docker push "$DOCKER_HUB_REGISTRY_IMAGE":"${CI_COMMIT_TAG#v}"
    - docker tag "$IMAGE_TAG" "$DOCKER_HUB_REGISTRY_IMAGE"
    - docker push "$DOCKER_HUB_REGISTRY_IMAGE"
    - docker logout "$DOCKER_HUB_REGISTRY"
  only:
    - tags

Deploy (staging):
  stage: deploy
  image: alpine
  environment: staging
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$STAGING_PRIVKEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$STAGING_SERVER_PUBKEY" > ~/.ssh/known_hosts
  script:
    - ssh -o PasswordAuthentication=no -o PreferredAuthentications=publickey -i ~/.ssh/id_rsa "$STAGING_SERVER_USER"@"$STAGING_SERVER" "$STAGING_DEPLOY_CMD"
  after_script:
    - rm -f ~/.ssh/id_rsa
  only:
    - dev
