image: node:latest

stages:
  - setup
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
  paths:
    - node_modules/
    - src/.next/
    - .env

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build app:
  stage: build
  script:
      - cp .env.example .env
      - npm install
      - npm run build

linting:
  stage: test
  script: npm run lint

unit tests:
  stage: test
  script: npm run test:coverage
  coverage: '/^Statements\s*:\s*([^%]+)/'

e2e tests:
  stage: test
  image: 'https://gitlab.tubit.tu-berlin.de/innodoc/innodoc-webapp.git#e2e:e2e'
  script: npm run test:e2e:ci

deploy staging:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$STAGING_PRIVKEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$STAGING_SERVER_PUBKEY" > ~/.ssh/known_hosts
  script:
    - ssh -o PasswordAuthentication=no -o PreferredAuthentications=publickey -i ~/.ssh/id_rsa $STAGING_SERVER_USER@$STAGING_SERVER "$STAGING_DEPLOY_CMD"
  environment: staging
  only:
    - master
  cache: {}
