stages:
  - setup
  - build
  - test

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/
    - src/.next

variables:
  DEBIAN_FRONTEND: noninteractive
  GIT_SUBMODULE_STRATEGY: recursive
  NVM_DIR: /root/.nvm

before_script:
  - apt-get -qq update && apt-get -qq -y install wget
  - whoami
  - who am i
  - ls /root
  - ls /root/.nvm
  - wget -q -O - https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - $NVM_DIR/nvm.sh
  - ls /root
  - ls /root/.nvm
  - nvm install node
  - nvm use node

install_node_modules:
  stage: setup
  script:
    - npm install

build_next:
  stage: build
  script: npm run build

lint:
  stage: test
  script: npm run lint

jest:
  stage: test
  script: npm test
