enableColors: true

packageExtensions:
  less-plugin-variables-output@*:
    dependencies:
      mkdirp: ^1.0.4

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.13.cjs
