enableColors: true
# pnpMode: loose
yarnPath: .yarn/releases/yarn-2.2.2.cjs
packageExtensions:
  antd@*:
    dependencies:
      css-loader: ^4.2.2
      ignore-loader: ^0.1.2
      less-loader: ^6.2.0
      null-loader: ^4.0.0
      postcss-loader: ^3.0.0
  debug@*:
    peerDependencies:
      supports-color: ^6.1.0
    peerDependenciesMeta:
      supports-color:
        optional: true
  '@eslint/eslintrc@*':
    dependencies:
      globals: ^13.2.0
      ignore: ^5.1.8
      js-yaml: ^3.14.0
      lodash: ^4.17.20
      minimatch: ^3.0.4
  extract-css-chunks-webpack-plugin@*:
    dependencies:
      webpack: ^4.44.1
  '@fortawesome/fontawesome-free@*':
    dependencies:
      react: ^16.13.1
  ionicons@*:
    dependencies:
      react: ^16.13.1
  next@*:
    dependencies:
      caniuse-lite: ^1.0.30001117
  next-i18next@*:
    dependencies:
      '@babel/runtime': ^7.10.4
      regenerator-runtime: ^0.13.7
  next-redux-saga@*:
    dependencies:
      '@babel/runtime': ^7.10.4
      react: ^16.13.1
  node-fetch@*:
    dependencies:
      encoding: ^0.1.13
  rc-animate@*:
    dependencies:
      react: ^16.13.1
      react-dom: ^16.13.1
  rc-checkbox@*:
    dependencies:
      react: ^16.13.1
  rc-collapse@*:
    dependencies:
      react: ^16.13.1
  rc-dialog@*:
    dependencies:
      react: ^16.13.1
      react-dom: ^16.13.1
  rc-menu@*:
    dependencies:
      react: ^16.13.1
      react-dom: ^16.13.1
  rc-progress@*:
    dependencies:
      react: ^16.13.1
  rc-tabs@*:
    dependencies:
      react: ^16.13.1
  rc-tooltip@*:
    dependencies:
      react: ^16.13.1
  rc-trigger@*:
    dependencies:
      react: ^16.13.1
      react-dom: ^16.13.1
  rc-util@*:
    dependencies:
      react: ^16.13.1
      react-dom: ^16.13.1
  promise-inflight@*:
    peerDependencies:
      bluebird: ^3.5.3
    peerDependenciesMeta:
      bluebird:
        optional: true
