enableColors: true

pnpEnableEsmLoader: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  less-plugin-variables-output@*:
    dependencies:
      mkdirp: ^1.0.4
