enableColors: true

packageExtensions:
  "@eslint/eslintrc@*":
    dependencies:
      globals: ^13.2.0
      ignore: ^5.1.8
      js-yaml: ^3.14.0
      lodash: ^4.17.20
      minimatch: ^3.0.4
  "@fortawesome/fontawesome-free@*":
    dependencies:
      react: ^16.13.1
  "@shelf/jest-mongodb@*":
    dependencies:
      jest-environment-node: ^26.3.0
  antd@*:
    dependencies:
      css-loader: ^4.2.2
      ignore-loader: ^0.1.2
      less-loader: ^6.2.0
      null-loader: ^4.0.0
      postcss-loader: ^3.0.0
      webpack: ^4.44.1
  debug@*:
    peerDependencies:
      supports-color: ^6.1.0
    peerDependenciesMeta:
      supports-color:
        optional: true
  extract-css-chunks-webpack-plugin@*:
    dependencies:
      webpack: ^4.44.1
  ionicons@*:
    dependencies:
      react: ^16.13.1
  jest-enzyme@*:
    dependencies:
      react: ^16.13.1
  jest-playwright-preset@*:
    dependencies:
      jest-runner: ^26.4.2
      playwright-chromium: ^1.4.0
  less-plugin-variables-output@*:
    dependencies:
      mkdirp: ^1.0.4
  next-i18next@*:
    dependencies:
      "@babel/runtime": ^7.10.4
      regenerator-runtime: ^0.13.7
  next-redux-saga@*:
    dependencies:
      "@babel/runtime": ^7.10.4
      react: ^16.13.1
  next@*:
    dependencies:
      caniuse-lite: ^1.0.30001117
  node-fetch@*:
    dependencies:
      encoding: ^0.1.13
  promise-inflight@*:
    peerDependencies:
      bluebird: ^3.5.3
    peerDependenciesMeta:
      bluebird:
        optional: true
  rc-animate@*:
    dependencies:
      react: ^16.13.1
      react-dom: ^16.13.1
  rc-cascader@*:
    dependencies:
      react: ^16.13.1
  rc-checkbox@*:
    dependencies:
      react: ^16.13.1
  rc-collapse@*:
    dependencies:
      react: ^16.13.1
  rc-dialog@*:
    dependencies:
      react: ^16.13.1
      react-dom: ^16.13.1
  rc-input-number@*:
    dependencies:
      react: ^16.13.1
  rc-mentions@*:
    dependencies:
      react-dom: ^16.13.1
  rc-menu@*:
    dependencies:
      react: ^16.13.1
      react-dom: ^16.13.1
  rc-picker@*:
    dependencies:
      react: ^16.13.1
  rc-progress@*:
    dependencies:
      react: ^16.13.1
  rc-rate@*:
    dependencies:
      react: ^16.13.1
  rc-tabs@*:
    dependencies:
      react: ^16.13.1
      react-dom: ^16.13.1
  rc-tooltip@*:
    dependencies:
      react: ^16.13.1
  rc-trigger@*:
    dependencies:
      react: ^16.13.1
      react-dom: ^16.13.1
  rc-upload@*:
    dependencies:
      react: ^16.13.1
  rc-util@*:
    dependencies:
      react: ^16.13.1
      react-dom: ^16.13.1
  redux-saga-test-plan@*:
    dependencies:
      "@redux-saga/is": ^1.1.2
      "@redux-saga/symbols": ^1.1.2

yarnPath: .yarn/releases/yarn-2.4.0.cjs
