import type { PageContextBuiltIn } from 'vite-plugin-ssr'
import type { PageContextBuiltInClient } from 'vite-plugin-ssr/client/router'

import type { RootState } from '@/store/makeStore'

import type { Locale } from './common'

export type PageProps = Record<string, never>

/** Custom client-side page context. */
export type PageContextClient = Omit<PageContextBuiltInClient, 'Page'> &
  Pick<PageContextServer, 'documentProps' | 'locale' | 'Page' | 'pageProps' | 'PRELOADED_STATE'>

/** Custom server-side page context. */
export type PageContextServer = Omit<PageContextBuiltIn, 'Page'> & {
  /** Styles generated by Emotion. */
  emotionStyleTags: string

  /** Rendered page HTML. */
  pageHtml: string

  /** Preloaded store state. */
  PRELOADED_STATE?: RootState

  /** Document meta data. */
  documentProps?: {
    /** Page title. */
    title?: string
    /** Page description. */
    description?: string
  }

  /** Current locale. */
  locale: Locale

  Page: PageComponent

  pageProps: PageProps
}

/** The `export { Page }` of `.page.js` file. */
type PageComponent = (pageProps: PageProps) => React.ReactElement | null
