import type { IconifyJSON } from '@iconify/types'
import mdiIconsJson from '@iconify-json/mdi/icons.json' with { type: 'json' }
import { ICON_NAMES } from '@innodoc/shared-core/icons'
import parseIconSvg from './parse-icon-svg.js'

const mdiIcons: IconifyJSON = mdiIconsJson

/** Resolve the path data (`d` attribute) of a single icon name (e.g. `mdi:home`) from the MDI icon set. */
function getIconPathData(name: string): string {
  const colonIndex = name.indexOf(':')
  if (colonIndex === -1 || name.slice(0, colonIndex) !== mdiIcons.prefix) {
    throw new Error(`Icon '${name}': only '${mdiIcons.prefix}' icons are supported`)
  }

  const shortName = name.slice(colonIndex + 1)
  const icon = mdiIcons.icons[shortName]
  if (!icon || typeof icon.body !== 'string') {
    throw new Error(`Icon '${name}' not found in the '${mdiIcons.prefix}' icon set`)
  }

  const { width = 24, height = 24 } = mdiIcons
  return parseIconSvg(`<svg viewBox='0 0 ${String(width)} ${String(height)}'>${icon.body}</svg>`)
}

/**
 * Development icon bundle.
 *
 * Resolves the `ICON_NAMES` manifest against the full MDI icon set at module load, so
 * adding an icon to the manifest takes effect in dev immediately (no build step).
 * In production, `#icon-bundle` resolves to the prebuilt `dist/icon-bundle.json`
 * generated by `scripts/build-icon-bundle.ts`.
 */
const iconBundle: Record<string, string> = {}
for (const name of ICON_NAMES) {
  iconBundle[name] = getIconPathData(name)
}

export default iconBundle
