import { assert, expect, test } from 'vitest'
import getSectionsApi from '@innodoc/shared-store/slices/content/sections'
import { createTestHarness, screen, within } from '@innodoc/ui-test-utils'
import { StaticToc } from '#toc'

// Section titles are generated by a seeded faker, and its word list moves between releases. What is
// pinned down here is the tree: how many links each level contributes, and the numbering the tree
// view prefixes them with.
test('StaticToc renders the section tree with its nesting', async () => {
  const harness = createTestHarness()
  await harness.withCourse()

  harness.render(<StaticToc />)

  expect(screen.getAllByRole('link')).toHaveLength(84)

  // 1st section has no children
  const firstItem = screen.getAllByRole('listitem').at(0)
  assert(firstItem, 'firstItem not found')
  expect(within(firstItem).getAllByRole('link')).toHaveLength(1)
  expect(within(firstItem).getByRole('link')).toHaveTextContent(/^1 [^\d].*/u)

  // 2nd section has 4 children, listed below it
  const secondItem = screen.getAllByRole('listitem').at(1)
  assert(secondItem, 'secondItem not found')

  const subSections = within(secondItem).getAllByRole('link')
  expect(subSections).toHaveLength(5)
  expect(subSections.map((section) => section.textContent.split(' ').at(0))).toEqual(['2', '2.1', '2.2', '2.3', '2.4'])
})

// The fixture course nests five levels deep (shared-fixtures `make-sections.ts`), so this is the
// check that the list is a real tree and not a flattened-with-indentation one: every link carries
// the numbering of its own path, and sits in exactly as many <ul> ancestors as it has number parts.
test('StaticToc indents every section one level below its parent', async () => {
  const harness = createTestHarness()
  await harness.withCourse()
  harness.render(<StaticToc />)

  const links = screen.getAllByRole('link').map((link) => ({
    number: link.textContent.split(' ').at(0) ?? '',
    depth: listAncestors(link).length,
  }))

  assert(
    links.some((link) => link.depth === 5),
    'the fixture course should nest five levels deep',
  )
  for (const { number, depth } of links) {
    expect(number.split('.')).toHaveLength(depth)
  }
})

// Subscription fan-out guard: the tree used to be assembled per node -
// `SectionItem` ran its own `useSelectSectionChildren` - so a course of N sections mounted N+1 RTK
// Query subscriptions to the same query, and every store notification walked all of them. The whole
// list must come from one subscription, handed down as props.
test('StaticToc subscribes to the sections query once for the whole tree', async () => {
  const harness = createTestHarness()
  await harness.withCourse()

  // `withCourse()` leaves one subscription of its own behind; only the delta belongs to the TOC
  const baseline = sectionSubscriptions(harness)

  const { unmount } = harness.render(<StaticToc />)

  expect(screen.getAllByRole('link')).toHaveLength(84)
  expect(sectionSubscriptions(harness) - baseline).toBe(1)

  unmount()
  expect(sectionSubscriptions(harness)).toBe(baseline)
})

/** Live RTK Query subscriptions to `getCourseSections`, as the query middleware counts them. */
function sectionSubscriptions(harness: ReturnType<typeof createTestHarness>): number {
  const cacheKey = Object.keys(harness.store.getState().contentApi.queries).find((key) =>
    key.startsWith('getCourseSections('),
  )
  assert(cacheKey, 'the fixture course should have its sections cached')

  // `internal_getRTKQSubscriptions` is RTK Query's own devtools handshake: it returns the
  // middleware's live subscription map, unlike the debounced copy of it in `state.contentApi`
  const subscriptions = harness.store.dispatch(
    getSectionsApi(harness.routeManager).internalActions.internal_getRTKQSubscriptions(),
  ) as unknown as { getSubscriptionCount: (queryCacheKey: string) => number }

  return subscriptions.getSubscriptionCount(cacheKey)
}

/** Every `<ul>` the element is nested in, innermost first. */
function listAncestors(element: Element): Element[] {
  const ancestors: Element[] = []
  for (let node = element.parentElement; node !== null; node = node.parentElement) {
    if (node.tagName === 'UL') {
      ancestors.push(node)
    }
  }
  return ancestors
}
