import { assert, expect, test } from 'vitest'
import { createTestHarness, screen, within } from '@innodoc/ui-test-utils'
import { StaticToc } from '#toc'

const harness = createTestHarness()

// Section titles are generated by a seeded faker, and its word list moves between releases. What is
// pinned down here is the tree: how many links each level contributes, and the numbering the tree
// view prefixes them with.
test('StaticToc renders the section tree with its nesting', async () => {
  await harness.withCourse()

  harness.render(<StaticToc />)

  expect(screen.getAllByRole('link')).toHaveLength(84)

  // 1st section has no children
  const firstItem = screen.getAllByRole('listitem').at(0)
  assert(firstItem, 'firstItem not found')
  expect(within(firstItem).getAllByRole('link')).toHaveLength(1)
  expect(within(firstItem).getByRole('link')).toHaveTextContent(/^1 [^\d].*/u)

  // 2nd section has 4 children, listed below it
  const secondItem = screen.getAllByRole('listitem').at(1)
  assert(secondItem, 'secondItem not found')

  const subSections = within(secondItem).getAllByRole('link')
  expect(subSections).toHaveLength(5)
  expect(subSections.map((section) => section.textContent.split(' ').at(0))).toEqual(['2', '2.1', '2.2', '2.3', '2.4'])
})
