---
overrides:
  # Allow to "omit" props using destructuring w/o having them marked as "unused"
  - files:
      - '**/*.tsx'
    rules:
      '@typescript-eslint/no-unused-vars': [error, { ignoreRestSiblings: true }]

  # Ignore vite-plugin-ssr special files
  - files:
      - pages/**/*.+(ts|tsx)
      - renderer/_+(default|error).page*.+(ts|tsx)
      - server/database/migrations/*.ts
    rules:
      filenames/match-exported: off
      filenames/match-regex: off
