---
overrides:
  # Page routing naming convenction
  - files:
      - pages/**/*.tsx
    rules:
      filenames/match-exported:
        - error
        - kebab
      filenames/match-regex:
        - error
        - ^[a-z-]+\.page$
        - false

  # Ignore vite-plugin-ssr special files
  - files:
      - renderer/_+(default|error).page*.tsx
    rules:
      filenames/match-exported: off
      filenames/match-regex: off

  # <ContentFragment /> as "recursive document renderer" needs import cycles
  - files:
      - ui/components/content/ContentFragment/**
    rules:
      import/no-cycle: off

  # AST content doesn't supply IDs for use as keys
  - files:
      - ui/components/content/ContentFragment/ast/**
    rules:
      react/no-array-index-key: off
