---
overrides:
  # Allow to "omit" props using destructuring w/o having them marked as "unused"
  - files:
      - '**/*.tsx'
    rules:
      '@typescript-eslint/no-unused-vars': [error, { ignoreRestSiblings: true }]

  # Ignore vite-plugin-ssr special files
  - files:
      - pages/**/*.+(ts|tsx)
      - renderer/_+(default|error).page*.+(ts|tsx)
      - server/database/migrations/*.ts
    rules:
      filenames/match-exported: off
      filenames/match-regex: off

  # <ContentFragment /> as "recursive document renderer" needs import cycles
  - files:
      - ui/components/content/ContentFragment/**
    rules:
      import/no-cycle: off

  # AST content doesn't supply IDs for use as keys
  - files:
      - ui/components/content/ContentFragment/ast/**
    rules:
      react/no-array-index-key: off
